### ISSUE TITLE
more errors from the merger

### ISSUE THREAD

**Issue by romanchyla** [adsabs/ADSimportpipeline#173]
```2017-10-27 00:23:36,130 ERROR    [17824:MainThread:__init__.py:432] Task=46394980-c387-4882-8eda-00e4d9d9cf00 failed.
     args=[{u'modtime': u'2017-10-27T00:23:26.020239Z', u'bibcode': u'1963JNuM....8..348.', u'text': {u'acknowledgement': []}, u'JSON_fingerprint': u'{"abs":[{"p":"/proj/ads/abstracts/phy/text/K63/K63-02793.abs","primary":1,"t":"1445375446"}],"links":{"electr":[{"u":"http://dx.doi.org/10.1016%2F0022-3115%2863%2990094-1"}]},"prop":["refereed"]}', u'entry_date': u'2013-11-05', u'metadata': [{u'comment': [], u'doi': [{u'origin': u'ELSEVIER', u'content': u'10.1016/0022-3115(63)90094-1'}], u'publication': {u'origin': u'ELSEVIER', u'dates': [{u'content': u'1963-05-00', u'type': u'date-published'}, {u'content': u'1963', u'type': u'publication_year'}], u'name': {u'raw': u'Journal of Nuclear Materials, Volume 8, Issue 3, p. 348-348.', u'canonical': u'Journal of Nuclear Materials'}, u'page_count': u'1', u'page_last': u'348', u'volume': u'8', u'page_range': u'348-348', u'electronic_id': None, u'altbibcode': u'1963JNuM....8..348.', u'issue': u'3', u'page': u'348'}, u'language': u'', u'tempdata': {u'origin': u'ELSEVIER', u'modtime': u'2015-10-20T21:10:46Z', u'type': u'general', u'primary': True, u'alternate_journal': False}, u'issns': [], u'conf_metadata': {u'origin': u'ELSEVIER', u'content': None}, u'titles': [{u'lang': u'en', u'text': u'Yc\u0442a\u043boc\u0442\u043d\u044be xapa\u043a\u0442ep\u0438c\u0442\u0438\u043a\u0438 ma\u0442ep\u0438a\u043bo\u0432 o\u0431o\u043bo\u0447\u043a\u0438 \u043cg\u2014z\u0433 \u0438 mg\u2014a1'}], u'isbns': [], u'authors': [{u'name': {u'western': u'\u0414o\u043b\u0434o\u043d, P.', u'normalized': None, u'native': None}, u'number': u'1', u'affiliations': [], u'orcid': None, u'type': u'regular', u'emails': []}], u'keywords': [], u'arxivcategories': [], u'pubnote': [], u'copyright': [{u'origin': u'ELSEVIER', u'content': u'(c) 1963 Elsevier Science B.V. All rights reserved.'}], u'abstracts': []}, {u'refereed': True, u'openaccess': False, u'eprint_openaccess': False, u'data_sources': [], u'pub_openaccess': False, u'tempdata': {u'origin': u'ADS metadata', u'modtime': None, u'type': u'properties', u'primary': False, u'alternate_journal': False}, u'doctype': {u'origin': u'ADS metadata', u'content': u'article'}, u'private': False, u'ocrabstract': False, u'associates': [], u'ads_openaccess': False, u'databases': [{u'origin': u'ADS metadata', u'content': u'PHY'}], u'vizier_tables': [], u'bibgroups': []}, {u'tempdata': {u'modtime': None, u'origin': u'ADS metadata', u'type': u'relations', u'primary': False, u'alternate_journal': False}, u'links': [{u'origin': None, u'count': None, u'title': None, u'url': u'http://dx.doi.org/10.1016%2F0022-3115%2863%2990094-1', u'access': None, u'type': u'electr'}], u'preprints': [], u'alternates': []}]}]
     kwargs={}
     trace=Traceback (most recent call last):
       File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 374, in trace_task
         R = retval = fun(*args, **kwargs)
       File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 629, in __protected_call__
         return self.run(*args, **kwargs)
       File "/app/aip/tasks.py", line 92, in task_merge_metadata
         r = solr_adapter.SolrAdapter.adapt(r)
       File "/app/aip/libs/solr_adapter.py", line 541, in adapt
         D = getattr(cls, '_%s' % k)(ADS_record)
       File "/app/aip/libs/solr_adapter.py", line 179, in _author_facet_hier
         r = u"0/%s" % (_normalize_author_name(author['name']['normalized']),)
       File "/app/aip/libs/solr_adapter.py", line 30, in _normalize_author_name
         return ' '.join(strname.split('.')).strip()
     AttributeError: 'NoneType' object has no attribute 'split'
     
2017-10-27 00:23:39,035 ERROR    [17818:MainThread:__init__.py:432] Task=9afbd222-1a28-4c25-893f-71d805b069e7 failed.
     args=[{u'modtime': u'2017-10-27T00:23:29.989108Z', u'bibcode': u'2003oiai.conf.....C', u'text': {u'acknowledgement': []}, u'JSON_fingerprint': u'{"abs":[{"p":"/proj/ads/abstracts/ast/text/J13/J13-45467.abs","primary":1,"t":"1298500238"}],"links":{"library":[{"u":"http://www.worldcat.org/isbn/8598138010"}]},"prop":["bibgroup: ESO/Lib"]}', u'entry_date': u'2004-02-12', u'metadata': [{u'comment': [], u'doi': [], u'publication': {u'origin': u'AUTHOR', u'dates': [{u'content': u'2003-12-00', u'type': u'date-published'}, {u'content': u'2003', u'type': u'publication_year'}], u'name': {u'raw': u'Optical and Infrared Astronomical Instrumentation for Modern Telescopes - Brazilian Workshop Editors - Bruno V. Castilho & Clemens D. Gneiding Location - Angra dos Reis, Rio de Janeiro, Brazil Date - November 16-20, 2003 Publisher - Laboratorio Nacional de Astrofisica Proceedings - published on CD-ROM ISBN - 85-98138-01-0', u'canonical': u'Optical and Infrared Astronomical Instrumentation for Modern Telescopes - Brazilian Workshop Editors - Bruno V. Castilho & Clemens D. Gneiding Location - Angra dos Reis'}, u'page_count': u'0', u'page_last': None, u'volume': None, u'page_range': None, u'electronic_id': None, u'altbibcode': u'2003oiai.conf.....C', u'issue': None, u'page': None}, u'language': u'', u'tempdata': {u'origin': u'AUTHOR', u'modtime': u'2011-02-23T22:30:38Z', u'type': u'general', u'primary': True, u'alternate_journal': False}, u'issns': [], u'conf_metadata': {u'origin': u'AUTHOR', u'content': None}, u'titles': [{u'lang': u'en', u'text': u'Optical and Infrared Astronomical Instrumentation for Modern Telescopes - Brazilian Workshop'}], u'isbns': [{u'origin': u'AUTHOR', u'content': [None, u'8598138010']}], u'authors': [{u'name': {u'western': u'Castilho, B. V.', u'normalized': u'Castilho, B', u'native': None}, u'number': u'1', u'affiliations': [], u'orcid': None, u'type': u'regular', u'emails': []}, {u'name': {u'western': u'Gneiding, C. D.', u'normalized': u'Gneiding, C', u'native': None}, u'number': u'2', u'affiliations': [], u'orcid': None, u'type': u'regular', u'emails': []}], u'keywords': [], u'arxivcategories': [], u'pubnote': [], u'copyright': [], u'abstracts': [{u'lang': u'en', u'text': u'The workshop was focused on optical and infrared instruments for large and medium class telescopes, with special attention on the projects that the Brazilian community is involved. Together with the instrumentation presentations the workshop had contributions about the science that these telescopes and new generation instruments will provide. This allowed the participants (instrumentation groups and the astronomers) interact and set the direction for the new developments needed to achieve the high quality data necessary to answer important open questions in many astronomy fields. Main Topics - Optical & Infrared Instruments - Software & Electronics - Science with New Generation Instruments', u'origin': u'AUTHOR'}]}, {u'refereed': False, u'openaccess': False, u'eprint_openaccess': False, u'data_sources': [], u'pub_openaccess': False, u'tempdata': {u'origin': u'ADS metadata', u'modtime': None, u'type': u'properties', u'primary': False, u'alternate_journal': False}, u'doctype': {u'origin': u'ADS metadata', u'content': u'proceedings'}, u'private': False, u'ocrabstract': False, u'associates': [], u'ads_openaccess': False, u'databases': [{u'origin': u'ADS metadata', u'content': u'AST'}], u'vizier_tables': [], u'bibgroups': [{u'origin': u'ADS metadata', u'content': u'ESO/Lib'}]}, {u'tempdata': {u'modtime': None, u'origin': u'ADS metadata', u'type': u'relations', u'primary': False, u'alternate_journal': False}, u'links': [{u'origin': None, u'count': None, u'title': None, u'url': u'http://www.worldcat.org/isbn/8598138010', u'access': None, u'type': u'library'}], u'preprints': [], u'alternates': []}]}]
     kwargs={}
     trace=Traceback (most recent call last):
       File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 374, in trace_task
         R = retval = fun(*args, **kwargs)
       File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 629, in __protected_call__
         return self.run(*args, **kwargs)
       File "/app/aip/tasks.py", line 93, in task_merge_metadata
         solr_adapter.SolrAdapter.validate(r)  # Raises AssertionError if not validated
       File "/app/aip/libs/solr_adapter.py", line 566, in validate
         assert len(set([type(i) for i in v])) == 1, "{0}: multiple data-types in list: {1}".format(k, v)
     AssertionError: isbn: multiple data-types in list: [u'8598138010', None]```

**Comment by romanchyla** [comment]
```root@adsvm06:/app# tail -f logs/import-pipeline.log
       File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 374, in trace_task
         R = retval = fun(*args, **kwargs)
       File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 629, in __protected_call__
         return self.run(*args, **kwargs)
       File "/app/aip/tasks.py", line 93, in task_merge_metadata
         solr_adapter.SolrAdapter.validate(r)  # Raises AssertionError if not validated
       File "/app/aip/libs/solr_adapter.py", line 572, in validate
         assert len(set([type(i) for i in v])) == 1, "{0}: multiple data-types in list: {1}".format(k, v)
     AssertionError: isbn: multiple data-types in list: [u'8598138010', None]
```
